# when using the bot, make sure to rename this to just "config.toml"

MAIN_TOKEN = "TOKEN"  # your discord bot token, of course!

DEV_GUILD_ID = 11111111111111111  # guild id that you own and that will not be used for a playerlist
BOT_COLOR = 12670688  # a color to color some embeds and all - it's nice for branding.

DOCKER_MODE = false  # whether or not the bot is running in docker. if it is, it'll automatically use the docker valkey and postgres, and you can leave the next two entries blank
DB_URL = "POSTGRESDB_URL"  # a url to a postgres database
VALKEY_URL = "VALKEY_URL"  # url to a valkey database

# worth noting for docker:
# - you'll need a .env file with a POSTGRES_PASSWORD entry (POSTGRES_PASSWORD="PASSWORD"). docker limitation, i would squeeze it in config.toml if i could

# - you can swap out the valkey for any redis 7.2 supporting backend, though i'd suggest keeping the name of the entry in the compose file "redis" because
# the bot relies on that to connect to it

SENTRY_DSN = "SENTRY_DSN" # the dsn for sentry. optional, you can leave it blank if you don't want to use it

# these next two are generated by the beginning instructions here:
# https://github.com/Astrea-Stellarium-Labs/elytra-ms#make-an-application
XBOX_CLIENT_ID = "ID"
XBOX_CLIENT_SECRET = "SECRET"

# you'll also need a token file called "tokens.json" in the root directory of the bot, generated by
# https://github.com/Astrea-Stellarium-Labs/elytra-ms#make-an-application
# the name is currently hardcoded, but i'll make it configurable in the future

OPENXBL_KEY = "KEY"  # register an account at https://xbl.io/ and you'll get a token to use

# bot list site tokens. leave blank or remove the entries if you don't want to use them
TOP_GG_TOKEN = ""
DBL_TOKEN = ""

# various emojis used throughout the bot. more or less self explanatory
GREEN_CIRCLE_EMOJI="RAW EMOJI STRING"
GRAY_CIRCLE_EMOJI="RAW EMOJI STRING"
WINDOWS_EMOJI_ID="EMOJI ID"
SWITCH_EMOJI_ID="EMOJI ID"
IOS_EMOJI_ID="EMOJI ID"
ANDROID_EMOJI_ID="EMOJI ID"
XBOX_ONE_EMOJI_ID="EMOJI ID"
XBOX_SERIES_EMOJI_ID="EMOJI ID"
PLAYSTATION_EMOJI_ID="EMOJI ID"
UNKNOWN_DEVICE_EMOJI_ID="EMOJI ID"

# the key used to encrypt premium codes. make this a very strong and random 64 character code
PREMIUM_ENCRYPTION_KEY = "KEY"